// src/routes/account/info.jsx
import axios from 'axios'
import Head from 'next/head'
import { useRouter } from 'next/router'
import { useEffect, useState } from 'react'
import { getGlobalState } from 'utils/globalState'
import Link from 'next/link'
import getAuth from 'utils/getAuth'
import connectDB from 'utils/connectDB'
import userModel from 'models/userModel'


export default function component(props) {
  let {  user } = JSON.parse(props.props)

  let router = useRouter()

  return (
    <div>
      <Head>
        <title>Account</title>
      </Head>

      <div className="rounded-lg bg-white pl-2 text-black">
        <h1 className=" text-2xl font-semibold">Account Details</h1>
        <div>
          <p>
            <b>Email:</b> {user.email}
          </p>
          <p>
            <b>Joined:</b> {user.createdAt}
          </p>
        </div>
        {/* <a onClick={() => setView(!view)} className="text-xl font-semibold">
          {view === true ? 'Edit' : 'View'}
        </a>
        :{view === true ? <View user={user}></View> : 'hi'} */}
      </div>
    </div>
  )
}

export async function getServerSideProps({ query, req }) {
  let auth = await getAuth(req.cookies.refreshToken)
  if (auth.error || !req.cookies.refreshToken) {
    return {
      redirect: {
        destination: '/signin',
      },
    }
  }
  connectDB()

  let user = await userModel.findOne({
    email: auth.user.email,
  })

  return {
    props: { props: JSON.stringify({ auth: auth, user: user }) },
  }
}

// src/routes/account/info/+page.svelte
<script>
	import axios from 'axios'
	import Product from '@src/routes/product/product.svelte'
	import { auth } from '@src/app.js'
	import { onMount } from 'svelte'
	import { page } from '$app/stores'
	import cookie from 'js-cookie'
	import { goto } from '$app/navigation'

	var user = null
	var error = null

	onMount(async function () {
		if (cookie.get('auth')) {
			$auth = JSON.parse(cookie.get('auth'))
		}
		var res = await axios.post($page.url.pathname, {
			email: JSON.parse(cookie.get('auth')).user.email,
		})
		if (res.data.error) {
			error = res.data.error
		}
		user = res.data.user
	})
</script>

<svelte:head><title>Account Info - Denify</title></svelte:head>

{#if user}
	<div class="rounded-lg bg-white pl-2 text-black">
		<p class=" text-lg font-semibold">Account Details</p>
		<div>
			<p>
				<b>Email:</b>
				{user.email}
			</p>
			<p>
				<b>Joined:</b>
				{user.createdAt}
			</p>
		</div>
	</div>
{:else}
	<p>Loading...</p>
{/if}
