// src/routes/account/profile.jsx
import axios from 'axios'
import Head from 'next/head'
import router, { useRouter } from 'next/router'
import { useEffect, useState } from 'react'
import { getGlobalState } from 'utils/globalState'
import ProductItem from 'components/product/item'
import Link from 'next/link'
import getAuth from 'utils/getAuth'
import connectDB from 'utils/connectDB'
import productModel from 'models/productModel'


export default function component(props) {
  let {  products, email } = JSON.parse(props.props)
  let router = useRouter()

  async function handleSendMessage(e) {
    e.preventDefault()
    let res = await axios.post('/api/user/setMessageEmails', {
      email: getGlobalState('auth').user.email,
      anothersEmail: email,
    })
    if (res.data.success) {
      router.push('/account/messages?recipEmail=' + email + '#latest')
    }
  }

  return (
    <div>
      <Head>
        <title>Profile - {email}</title>
      </Head>

      <div className="">
        <h1 className="mb-10 text-2xl font-semibold">{email}'s Products</h1>
        {getGlobalState('auth').user && (
          <a
            onClick={(e) => handleSendMessage(e)}
            className="hover:text-gray-400 cursor-pointer"
          >
            Message
          </a>
        )}

        <div className="flex flex-wrap text-white">
          {products.length === 0 ? (
            <h2>No Products</h2>
          ) : (
            products.map((product) => (
              <ProductItem key={product._id} product={product} />
            ))
          )}
        </div>
      </div>
    </div>
  )
}

export async function getServerSideProps({ query: { email }, req }) {
  let auth = await getAuth(req.cookies.refreshToken)
  if (auth.error || !req.cookies.refreshToken) {
    // return {
    //   redirect: {
    //     destination: '/signin',
    //   },
    // }
  }
  connectDB()

  let products = await productModel.find({
    email: email,
  })

  return {
    props: { props: JSON.stringify({ auth, products, email }) },
  }
}

// src/routes/account/profile.svelte
<script>
	import axios from 'axios';
	import Product from '@src/components/product.svelte';
	import { auth } from '@src/utils/store';
	import { onMount } from 'svelte';
	import { page } from '$app/stores';
	import cookie from 'js-cookie';
	import { goto } from '$app/navigation';

	var products = null;
	var error = null;
	var email = $page.url.searchParams.get('email');

	onMount(async function () {
		if (cookie.get('auth')) {
			$auth = JSON.parse(cookie.get('auth'));
		}
		var res = await axios.post('/api/user/account/getProfile', {
			email
		});
		if (res.data.error) {
			error = res.data.error;
		}
		products = res.data.products;
	});

	async function sendMessage() {
		var res = await axios.post('/api/user/account/setContacts', {
			email: JSON.parse(cookie.get('auth')),
			recipEmail: email
		});
		if (res.data.success) {
			goto('/account/messages?recipEmail=' + email + '#latest');
		}
	}
</script>

<svelte:head><title>Account Profile - {email}</title></svelte:head>

{#if products && email}
	<h1 class="mb-5 text-lg font-semibold">{email}'s Products</h1>
	<button on:click={sendMessage} class=" mb-5 hover:text-gray-400 cursor-pointer"> Message </button>
	<div class="flex flex-wrap text-white">
		{#if products.length === 0}
			<h2>No Products found.</h2>
		{:else}
			{#each products as product}
				<Product {product} />
			{/each}
		{/if}
	</div>
{:else}
	<h1>Loading...</h1>
{/if}
